### PR TITLE
feat(indexer/name_service): use event logs to support ENS feed

### PR DESCRIPTION
**Pull request by brucexc**
burn->mint
```
{
-  "timestamp": "2022-12-12T22:10:11Z",
+  "timestamp": "2022-12-12T17:10:11-05:00",
   "hash": "0x61e483fd5211fb893f2776b184844a04790d0e8651cc68eb7c046b0cf84df34d",
   "network": "ethereum",
+  "platform": "ENS Registrar",
   "tag": "collectible",
-  "type": "burn",
+  "type": "mint",
   "success": true,
   "created_at": "2022-12-12T22:12:37.66773Z",
   "updated_at": "2022-12-12T22:12:37.66773Z",
   "actions": [
     {
-      "tag": "transaction",
-      "type": "transfer",
-      "index": -1,
-      "address_from": "0xf4f12c86954a7fc56b7442b109c6b12bd4997261",
-      "address_to": "0x283af0b28c62c092c9727f1ee09c02ca627eb7f5",
-      "metadata": {
-        "name": "Ethereum",
-        "image": "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
-        "value": "13817535077553640",
-        "symbol": "ETH",
-        "decimals": 18,
-        "standard": "Native",
-        "value_display": "0.01381753507755364"
-      },
-      "related_urls": [
-        "https://etherscan.io/tx/0x61e483fd5211fb893f2776b184844a04790d0e8651cc68eb7c046b0cf84df34d"
-      ]
-    },
-    {
-      "tag": "collectible",
-      "type": "burn",
-      "index": 218,
-      "address_from": "0xa791e22e02de1070313169066463c815c92c0b17",
-      "address_to": "0x0000000000000000000000000000000000000000",
-      "metadata": {
-        "id": "31864508811257966461047380508284306946703749800207674638886733542382546544496",
-        "name": "🌐www.eth",
-        "image": "https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/0x4672ac40b6a8f93d2fa99e0bfee666d304d62d47d8a38bf9e4cf02eab4396770/image",
-        "value": "1",
-        "symbol": "ENS",
-        "standard": "ERC-721",
-        "attributes": [
-          {
-            "value": "number",
-            "trait_type": "number"
-          },
-          {
-            "value": 4,
-            "trait_type": "Segment Length"
-          },
-          {
-            "value": "mixed",
-            "trait_type": "Character Set"
-          },
-          {
-            "value": "string",
-            "trait_type": "string"
-          },
-          {
-            "value": 1670883011000,
-            "trait_type": "Registration Date"
-          },
-          {
-            "value": 1657110629000,
-            "trait_type": "Created Date"
-          },
-          {
-            "value": "date",
-            "trait_type": "date"
-          },
-          {
-            "value": 4,
-            "trait_type": "Length"
-          },
-          {
-            "value": 1674038706000,
-            "trait_type": "Expiration Date"
-          }
-        ],
-        "collection": "🌐www.eth",
-        "description": "🌐www.eth, an ENS name.",
-        "external_link": "https://app.ens.domains/name/🌐www.eth",
-        "value_display": "1",
-        "contract_address": "0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85"
-      },
-      "related_urls": [
-        "https://etherscan.io/tx/0x61e483fd5211fb893f2776b184844a04790d0e8651cc68eb7c046b0cf84df34d",
-        "https://opensea.io/assets/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/31864508811257966461047380508284306946703749800207674638886733542382546544496",
-        "https://looksrare.org/collections/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/31864508811257966461047380508284306946703749800207674638886733542382546544496"
-      ]
-    },
-    {
       "tag": "collectible",
       "type": "mint",
-      "index": 219,
-      "address_from": "0x0000000000000000000000000000000000000000",
+      "index": 227,
+      "address_from": "0xf4f12c86954a7fc56b7442b109c6b12bd4997261",
       "address_to": "0x283af0b28c62c092c9727f1ee09c02ca627eb7f5",
@@ -111,6 +30,2 @@
           {
-            "value": "string",
-            "trait_type": "string"
-          },
-          {
             "value": 1670883011000,
@@ -119,15 +34,3 @@
           {
-            "value": 1657110629000,
-            "trait_type": "Created Date"
-          },
-          {
-            "value": 4,
-            "trait_type": "Segment Length"
-          },
-          {
-            "value": "mixed",
-            "trait_type": "Character Set"
-          },
-          {
-            "value": 1674038706000,
+            "value": 1677194401000,
             "trait_type": "Expiration Date"
@@ -143,40 +46,4 @@
           {
-            "value": "number",
-            "trait_type": "number"
-          }
-        ],
-        "collection": "🌐www.eth",
-        "description": "🌐www.eth, an ENS name.",
-        "external_link": "https://app.ens.domains/name/🌐www.eth",
-        "value_display": "1",
-        "contract_address": "0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85"
-      },
-      "platform": "ENS Registrar",
-      "related_urls": [
-        "https://etherscan.io/tx/0x61e483fd5211fb893f2776b184844a04790d0e8651cc68eb7c046b0cf84df34d",
-        "https://opensea.io/assets/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/31864508811257966461047380508284306946703749800207674638886733542382546544496",
-        "https://looksrare.org/collections/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/31864508811257966461047380508284306946703749800207674638886733542382546544496"
-      ]
-    },
-    {
-      "tag": "collectible",
-      "type": "transfer",
-      "index": 226,
-      "address_from": "0x283af0b28c62c092c9727f1ee09c02ca627eb7f5",
-      "address_to": "0xf4f12c86954a7fc56b7442b109c6b12bd4997261",
-      "metadata": {
-        "id": "31864508811257966461047380508284306946703749800207674638886733542382546544496",
-        "name": "🌐www.eth",
-        "image": "https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/0x4672ac40b6a8f93d2fa99e0bfee666d304d62d47d8a38bf9e4cf02eab4396770/image",
-        "value": "1",
-        "symbol": "ENS",
-        "standard": "ERC-721",
-        "attributes": [
-          {
             "value": 4,
-            "trait_type": "Length"
-          },
-          {
-            "value": "number",
-            "trait_type": "number"
+            "trait_type": "Segment Length"
           },
@@ -187,14 +54,2 @@
           {
-            "value": 1657110629000,
-            "trait_type": "Created Date"
-          },
-          {
-            "value": "date",
-            "trait_type": "date"
-          },
-          {
-            "value": 4,
-            "trait_type": "Segment Length"
-          },
-          {
             "value": "string",
@@ -203,8 +58,8 @@
           {
-            "value": 1670883011000,
-            "trait_type": "Registration Date"
+            "value": 1657110629000,
+            "trait_type": "Created Date"
           },
           {
-            "value": 1674038706000,
-            "trait_type": "Expiration Date"
+            "value": "number",
+            "trait_type": "number"
           }
```

### CODE REVIEW

**Comment by brucexc** [comment]
r-1321

**Comment by brucexc** [comment]
```
{
    "timestamp": "2023-04-24T02:12:47-04:00",
    "hash": "0xbb73f618294dde570537b9445c6df4145402e916f00f34626b22c78541ee9004",
    "owner": "0x934b510d4c9103e6a87aef13b816fb080286d649",
    "fee": "0.005064831413988384",
    "address_from": "0x934b510d4c9103e6a87aef13b816fb080286d649",
    "address_to": "0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85",
    "network": "ethereum",
    "platform": "ENS Registrar",
    "tag": "collectible",
    "type": "edit",
    "success": true,
    "created_at": "2023-04-26T20:54:24.889212-04:00",
    "updated_at": "2023-04-26T20:54:24.889212-04:00",
    "actions": [
        {
            "tag": "collectible",
            "type": "edit",
            "index": 255,
            "address_from": "0x934b510d4c9103e6a87aef13b816fb080286d649",
            "address_to": "0xd4416b13d2b3a9abae7acd5d6c2bbdbe25686401",
            "metadata": {
                "name": "sujiyan.eth",
                "action": "wrap",
                "expiry": "2027-04-30T00:49:54-04:00"
            },
            "platform": "ENS Registrar",
            "related_urls": [
                "https://etherscan.io/tx/0xbb73f618294dde570537b9445c6df4145402e916f00f34626b22c78541ee9004"
            ]
        }
    ]
}
```

**Comment by brucexc** [comment]
r-1320

**Comment by brucexc** [comment]
```
{
    "timestamp": "2023-04-26T20:49:23-04:00",
    "hash": "0x7364fd343c669e29af6710ebc55c4e6588e8acb7d2b63afe2a00f09f1528ada8",
    "owner": "0xa60e522c5517b05526ee0f7f3885b82b37ceeb2d",
    "fee": "0.003529175103095238",
    "address_from": "0xa60e522c5517b05526ee0f7f3885b82b37ceeb2d",
    "address_to": "0x231b0ee14048e9dccd1d247744d114a4eb5e8e63",
    "network": "ethereum",
    "platform": "ENS Registrar",
    "tag": "collectible",
    "type": "edit",
    "success": true,
    "created_at": "2023-04-26T21:50:36.003659-04:00",
    "updated_at": "2023-04-26T21:50:36.003659-04:00",
    "actions": [
        {
            "tag": "collectible",
            "type": "edit",
            "index": 249,
            "address_from": "0xa60e522c5517b05526ee0f7f3885b82b37ceeb2d",
            "address_to": "0x231b0ee14048e9dccd1d247744d114a4eb5e8e63",
            "metadata": {
                "key": "avatar",
                "name": "pepetrillionaire.eth",
                "value": "https://ens.xyz/pepetrillionaire.eth",
                "action": "text"
            },
            "platform": "ENS Registrar",
            "related_urls": [
                "https://etherscan.io/tx/0x7364fd343c669e29af6710ebc55c4e6588e8acb7d2b63afe2a00f09f1528ada8"
            ]
        }
    ]
}
```

**Comment by brucexc** [comment]
r-1241

**Review by kallydev — APPROVED** [review]

**Pull request merged**
